	cmake_minimum_required(VERSION 2.6)
	add_executable(	for-loop-infinite src\loops\for-loop-infinite.c	)
	add_executable(	for-loop-nested src\loops\for-loop-nested.c	)
	add_executable(	break1 src\loops\break1.c	)
	add_executable(	macro-elif src\macro\macro-elif.c	)
	add_executable(	macro-ifdef-2 src\macro\macro-ifdef-2.c	)
	add_executable(	macro-ifdef src\macro\macro-ifdef.c	)
	add_executable(	macro-ifndef src\macro\macro-ifndef.c	)
	add_executable(	macro-undef src\macro\macro-undef.c	)
	add_executable(	macros-else src\macro\macros-else.c	)
