	cmake_minimum_required(VERSION 2.6)
	add_executable(	for-loop-diff-combination src\loops\for-loop-diff-combination.c	)
	add_executable(	for-loop-infinite src\loops\for-loop-infinite.c	)
	add_executable(	for-loop-nested src\loops\for-loop-nested.c	)
	add_executable(	for-loop1 src\loops\for-loop1.c	)
	add_executable(	for-loop2 src\loops\for-loop2.c	)
	add_executable(	goto src\loops\goto.c	)
	add_executable(	if src\loops\if.c	)
	add_executable(	if2 src\loops\if2.c	)
	add_executable(	if3 src\loops\if3.c	)
	add_executable(	nested_if src\loops\nested_if.c	)
	add_executable(	break1 src\loops\break1.c	)
	add_executable(	while-diff-combination src\loops\while-diff-combination.c	)
	add_executable(	while-loop1 src\loops\while-loop1.c	)
	add_executable(	while-loop2 src\loops\while-loop2.c	)
	add_executable(	while-nested src\loops\while-nested.c	)
	add_executable(	macro-1 src\macro\macro-1.c	)
	add_executable(	macro-2 src\macro\macro-2.c	)
	add_executable(	macro-elif src\macro\macro-elif.c	)
	add_executable(	macro-ifdef-2 src\macro\macro-ifdef-2.c	)
	add_executable(	macro-ifdef src\macro\macro-ifdef.c	)
	add_executable(	macro-ifndef src\macro\macro-ifndef.c	)
	add_executable(	macro-undef src\macro\macro-undef.c	)
	add_executable(	macros-else src\macro\macros-else.c	)
	add_executable(	typedef src\macro\typedef.c	)
	add_executable(	typedef2 src\macro\typedef2.c	)



